steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mach-439419/dp-docs:$COMMIT_SHA', '-f', 'Dockerfile', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mach-439419/dp-docs:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "mach-docs",
        "--image",
        "gcr.io/mach-439419/dp-docs:$COMMIT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

timeout: 900s
options:
 logging: CLOUD_LOGGING_ONLY